### ISSUE TITLE
Spurious KeyError: 'playlistlength' from MPD module

### ISSUE THREAD

**Issue by JakobOvrum** [enkore/i3pystatus#263]
I'm getting this error quite often when running i3pystatus (latest from `pip`):
```
> Exception in Thread-2 at Sun 11 Oct 2015 07:04:32, module MPD
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/modules.py", line 158, in __call__
    self.run()
  File "/usr/lib/python3.5/site-packages/i3pystatus/mpd.py", line 85, in run
    "len": int(status["playlistlength"]),
KeyError: 'playlistlength'
```
my MPD settings are as follows:
```py
status.register("mpd",
    format="{title}{status}{artist}",
    status={
        "pause": "▷",
        "play": "▶",
        "stop": "◾",
    },)
```
Using `mpd` from the Arch Linux repositories:
```
$ pacman -Q --search mpd
local/mpd 0.19.10-1
    Flexible, powerful, server-side application for playing music
```
Sometimes I see the error message flashing in the status bar after I take an application out of fullscreen, but it doesn't happen every time.

I regularly delete i3pystatus error log files due to this, as they pile up over time.

**Comment by enkore** [comment]
fixed in merged PR #264
