### ISSUE TITLE
Support for python 3.5

### ISSUE THREAD

**Issue by mihok** [enkore/i3pystatus#265]
Currently python 3.33 is required, on systems such as Arch Linux, which have updated to Python 3.5.0-2 it would be helpful to support python 3.5. As it stands right now, once you update Arch Linux, i3pystatus becomes unusable and returns: Error: status_command process exited unexpectedly (exit 1)

And trying to run it from the command line returns:
```
Traceback (most recent call last):
  File "/usr/bin/i3pystatus", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'i3pystatus==3.33' distribution was not found and is required by the application
```

**Comment by richese** [comment]
It works fine with python3.5 in Arch for me.

I think I had the same issue after the switch. I had to rebuild i3pystatus and all its dependencies that are from AUR to move the files from old 3.4 directory to the new 3.5 directory.

**Comment by Arvedui** [comment]
i3pystatus runs fine with python3.5

The problem is that it's still installed in /usr/lib/python3.4/ on your system.
You just need to rebuild the package.

**Comment by enkore** [comment]
When running Arch and updating Python you need to rebuild all Python AUR packages and reinstall everything that was installed with easy_install or pip.

**Comment by mihok** [comment]
Ah, sorry for my miscomment, after rebuilding each package it ended up working! Thanks!

**Comment by rubickcz** [comment]
I had similar issue when updating python 3.7 to 3.8 on Arch Linux. I can confirm that I had to rebuild i3pystatus package as well as several other python packages that are used by plugins.
