### ISSUE TITLE
Crash: Playerctl was imported without specifying a version first

### ISSUE THREAD

**Issue by binaryplease** [enkore/i3pystatus#307]
Hi,

I can't start i3pystatus anymore.

Error message:

```
/home/binaryplease/.i3_status.py:76: PyGIWarning: Playerctl was imported without specifying a version first. Use gi.require_version('Playerctl', '1.0') before import to ensure that the right version gets loaded.
  status.register("spotify")
Traceback (most recent call last):
  File "/home/binaryplease/.i3_status.py", line 80, in <module>
    format="♪ {volume}",format_muted="♪ MUTE")
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/__init__.py", line 93, in register
    return self.modules.append(module, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/util.py", line 73, in append
    module, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/imputil.py", line 47, in instanciate_class_from_module
    return self.instanciate_class_from_module(self.get_module(module), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/imputil.py", line 45, in instanciate_class_from_module
    return self.get_class(module)(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/modules.py", line 40, in __init__
    super(Module, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/settings.py", line 107, in __init__
    self.init()
  File "/usr/lib/python3.5/site-packages/i3pystatus/alsa.py", line 59, in init
    self.create_mixer()
  File "/usr/lib/python3.5/site-packages/i3pystatus/alsa.py", line 77, in create_mixer
    control=self.mixer, id=self.mixer_id, cardindex=self.card)
alsaaudio.ALSAAudioError: Unable to find mixer control Master,0 [hw:0]
```

**Comment by t3zla** [comment]
Could you post the output of the command
    amixer scontrols

**Comment by binaryplease** [comment]
binaryplease➜~(master✗)» amixer scontrols                            [14:56:58]
Simple mixer control 'Master',0
Simple mixer control 'Capture',0

**Comment by t3zla** [comment]
Could you post your i3pystatus configuration?

**Comment by binaryplease** [comment]
```
# -*- coding: utf-8 -*-

import subprocess

from i3pystatus import Status
from i3pystatus.mail import notmuchmail

status = Status(standalone=True)


#Date
status.register("clock",
        format="%a %-d %b %H:%M:%S",)

#CPU Temperature
status.register("temp",format="{temp}°C",file="/sys/class/thermal/thermal_zone1/temp")

status.register("cpu_usage",format="{usage_cpu0:3.0f}%{usage_cpu1:3.0f}%{usage_cpu2:3.0f}%{usage_cpu3:3.0f}%{usage_cpu4:3.0f}%{usage_cpu5:3.0f}%{usage_cpu6:3.0f}%{usage_cpu7:3.0f}%")

status.register("text", text="CPU",color="#00ffff")

#RAM
status.register("mem",format="{percent_used_mem}%",)

status.register("text", text="RAM",color="#00ffff")

#Battery
status.register("battery",
    battery_ident="BAT1",
    format="{status}/{consumption:.2f}W {percentage:.2f}% {remaining:%E%hh:%Mm}",
    alert=True,
    alert_percentage=5,
    status={
        "DIS": "↓",
        "CHR": "↑",
        "FULL": "=",
    },)

status.register("text", text="BATTERY",color="#00ffff")

# Network 
status.register("runwatch",
    name="DHCP",
    path="/var/run/dhc*.pid",)

status.register("network",
    interface="enp3s0",
    format_up="{v4} {bytes_recv:04.0f}kbs",
    format_down="")


status.register("network",
    interface="wlp4s0",
    format_up="{essid} {quality:03.0f}% {v4} {bytes_recv:04.0f}kbs",
    format_down="")

#status.register("network_traffic",
##    interface="wlp3s0",
#    format="{bytes_recv}/{bytes_sent}")

status.register("text", text="NETWORK",color="#00ffff")
#status.register("text", text="NETWORK",color="#00ffff",cmd_leftclick="urxvt -e bash -c 'ip addr && zsh'")

#Disk
status.register("disk",
    path="/",
    format="/ {percentage_used}% [{avail}G]",)
#status.register("text", text="DISK",color="#00ffff",cmd_leftclick="urxvt -e bash -c 'lsblk && df && zsh'")
status.register("text", text="DISK",color="#00ffff")

#spotify
status.register("spotify")

#Audio
status.register("alsa",
    format="♪ {volume}",format_muted="♪ MUTE")
status.register("text", text="VOLUME",color="#00ffff")


#Backlight
status.register("backlight",
    format="☀ {percentage}",)

#Mail
status.register("mail",
    backends=[ notmuchmail.Notmuch( account="personal")
    ],
    hide_if_null=True,
    format="{unread}",
    format_plural="{unread}")


status.register("text", text="MAIL",color="#00ffff")
#status.register("text", text="MAIL",color="#00ffff",cmd_leftclick="thunderbird &> /dev/null")

#Weather
status.register("weather",
    format="{current_temp} - {humidity}%",location_code="GMXX5686",colorize=True)

status.run()
```

**Comment by enkore** [comment]
What does `cat /proc/asound/cards` say?

**Comment by binaryplease** [comment]
```
binaryplease➜~(master✗)» cat /proc/asound/cards                      [15:08:05]
 0 [USB            ]: USB-Audio - Scarlett 2i2 USB
                      Focusrite Scarlett 2i2 USB at usb-0000:00:14.0-3.1.4, high speed
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xb4410000 irq 30
 2 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xb4000000 irq 17
```

**Comment by enkore** [comment]
Hm, the defaults should work then (card=0, mixer_id=0, mixer=Master) and control the "Focusrite Scarlett 2i2".

**Comment by t3zla** [comment]
Your setup doesn't work on my system either, I suspect you might just have a syntax error somewhere because running the alsa module exactly how you have it, set up by itself works.

**Comment by enkore** [comment]
If I comment lines 71 (I don't have spotify) and 80 through 89 out his config works for me.

**Comment by binaryplease** [comment]
I just tried my config without the alsa section (lins 73-78), that works fine.
