### ISSUE TITLE
Google calendar module displays only "GoogleCalendar: '_module'"

### ISSUE THREAD

**Issue by binaryplease** [enkore/i3pystatus#322]
Just added the google calendar module, my config:

https://gist.github.com/binaryplease/3add36eef50cd9a46c6e

Shows the error:

![2016-02-15-163737_1919x26_scrot](https://cloud.githubusercontent.com/assets/1719781/13053009/73bb46ae-d402-11e5-97bd-ad39da97d4f4.png)

**Comment by enkore** [comment]
Do you get a traceback in the log file? (~/.i3pystatus-XYZ)

**Comment by binaryplease** [comment]
Yes!

```
> Exception in Thread-2 at Mon 15 Feb 2016 05:35:34 PM CET, module GoogleCalendar
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/modules.py", line 241, in __call__
    self.run()
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/google_calendar.py", line 60, in run
    self.connect_service()
  File "/usr/lib/python3.5/site-packages/i3pystatus/google_calendar.py", line 83, in connect_service
    self.credentials = oauth2client.file.Storage(self.credential_path).get()
  File "/usr/lib/python3.5/site-packages/oauth2client/client.py", line 389, in get
    return self.locked_get()
  File "/usr/lib/python3.5/site-packages/oauth2client/file.py", line 81, in locked_get
    credentials = Credentials.new_from_json(content)
  File "/usr/lib/python3.5/site-packages/oauth2client/client.py", line 294, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```

**Comment by enkore** [comment]
Hm, that traceback reads like the issue is a missing key in the `/home/binaryplease/Documents/google_api_credentials.json` file. Maybe @facetoe has an idea?

**Comment by facetoe** [comment]
Yep, looks like an issue with your credentials. Did you follow the steps on https://developers.google.com/google-apps/calendar/quickstart/python? If you run the test program on that page does it succeed without error?

**Comment by binaryplease** [comment]
@facetoe Yes I followed that guide and can run the testprogram without errors

**Comment by facetoe** [comment]
Can you post a sanitized version of your `google_api_credentials.json` file? From that stack trace it looks like you are missing the:

```
"_module" : "oauth2client.client",
```
section.

**Comment by binaryplease** [comment]
`{"installed":{"client_id":"xxxxxxxxxxxxx-xxxxxxxxxxxxx.apps.googleusercontent.com","project_id":"xxxxxxxxxx","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_xxxxxx_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxxxxxxxxxxxx","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}
`

I changed the private parts with 'x' for the post, other than that it is like I downloaded it, no changes.

**Comment by facetoe** [comment]
That doesn't look right to me, here is mine as a reference:

```json
{
   "id_token" : null,
   "token_uri" : "https://accounts.google.com/o/oauth2/token",
   "user_agent" : "Google Calendar API Python Quickstart",
   "refresh_token" : "******",
   "_class" : "OAuth2Credentials",
   "scopes" : [
      "https://www.googleapis.com/auth/calendar.readonly"
   ],
   "client_secret" : "****",
   "invalid" : false,
   "token_info_uri" : "https://www.googleapis.com/oauth2/v2/tokeninfo",
   "client_id" : "******",
   "_module" : "oauth2client.client",
   "access_token" : "*********",
   "revoke_uri" : "https://accounts.google.com/o/oauth2/revoke",
   "token_expiry" : "*****",
   "token_response" : {
      "access_token" : "***",
      "expires_in" : ***,
      "token_type" : "Bearer"
   }
}
```

When you run the sample program it will take you through the oauth stuff and generate a file `~/.credentials/calendar-python-quickstart.json`. Can you see this file?

**Comment by binaryplease** [comment]
Ok, I was using the wrong file (the downloaded instead of the one that gets created automatically)
I changed the path to the correct one, now it only shows the string:

`GoogleCalendar: 'dateTime'`

The credentials file looks like yours now:

```
{
	"user_agent": "Google Calendar API Python Quickstart",
	"_class": "OAuth2Credentials",
	"id_token": null,
	"invalid": false,
	"client_secret": "*********",
	"access_token": "******",
	"_module": "oauth2client.client",
	"token_uri": "https://accounts.google.com/o/oauth2/token",
	"token_info_uri": "https://www.googleapis.com/oauth2/v2/tokeninfo",
	"token_expiry": "******",
	"scopes": ["https://www.googleapis.com/auth/calendar.readonly"],
	"revoke_uri": "https://accounts.google.com/o/oauth2/revoke",
	"client_id": "******",
	"token_response": {
		"access_token": "********",
		"token_type": "Bearer",
		"expires_in": ****,
		"refresh_token": "*******"
	},
	"refresh_token": "********"
}
```

**Comment by facetoe** [comment]
Looks like you're missing a dependancy. Have you installed all the module dependancies? You probably need `dateutil` which I think is `python-dateutil` in pip.

**Comment by facetoe** [comment]
Actually, I take it back. Looks like a bug.

**Comment by facetoe** [comment]
What does your next event in GoogleCalendar look like? Does it have a start time?

**Comment by binaryplease** [comment]
@facetoe I found that i works with events that have a start time.
Mine didn't have a specific time because it was a birthday, if I add an upcoming event with specific time it works. 

I have a lot of events with no time specified, it would be nice if these where supported too, I guess it's not that complicated to implement.

**Comment by facetoe** [comment]
That makes sense. Yes should be easy to support, I'll have a look at it tomorrow as it's getting a bit late here.

**Comment by binaryplease** [comment]
@facetoe Is this fixed? I'm still getting this error.
The traceback shows:


```
2016-08-03 14:37:35,497 [ERROR   ][i3pystatus.google_calendar.GoogleCalendar 76] Exception in Thread-3 at Mi 03 Aug 2016 14:37:35 CEST, module GoogleCalendar
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/util.py", line 348, in wrapper
    return method(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/google_calendar.py", line 71, in run
    self.connect_service()
  File "/usr/lib/python3.5/site-packages/i3pystatus/google_calendar.py", line 95, in connect_service
    self.credentials = oauth2client.file.Storage(self.credential_path).get()
  File "/usr/lib/python3.5/site-packages/oauth2client/client.py", line 389, in get
    return self.locked_get()
  File "/usr/lib/python3.5/site-packages/oauth2client/file.py", line 81, in locked_get
    credentials = Credentials.new_from_json(content)
  File "/usr/lib/python3.5/site-packages/oauth2client/client.py", line 294, in new_from_json
    module_name = data['_module']
KeyError: '_module'

```

**Comment by facetoe** [comment]
Are you sure your credentials JSON is correct? It looks like it is missing the "_module" key. Are able to run the [Google demo code](https://developers.google.com/google-apps/calendar/quickstart/python) using your credentials?

**Comment by binaryplease** [comment]
Hi, I generated the credentials  again following the tutorial at https://developers.google.com/google-apps/calendar/quickstart/python

My json does in fact not have a '_module' part.

I tried the quickstart example and it doesnt work either. The error is similar:
```

Traceback (most recent call last):
  File "caltest.py", line 79, in <module>
    main()
  File "caltest.py", line 60, in main
    credentials = get_credentials()
  File "caltest.py", line 43, in get_credentials
    credentials = store.get()
  File "/usr/lib/python3.5/site-packages/oauth2client/client.py", line 409, in get
    return self.locked_get()
  File "/usr/lib/python3.5/site-packages/oauth2client/file.py", line 65, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/lib/python3.5/site-packages/oauth2client/client.py", line 304, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```

Is this an error or am I doing something wrong?

**Comment by binaryplease** [comment]
Sorry, nervermind. I generated them wrong.

**Comment by LucaCappelletti94** [comment]
How did you manage to solve it? I'm facing the very same issue but I don't see any other way to generate the file.

**Comment by facetoe** [comment]
Hmmm It's been a long time since I used this module, but @chestm007 might be able to help you out.

**Comment by chestm007** [comment]
I've figured this out, give me a few minutes to put together a proper response :smile:

**Comment by chestm007** [comment]
The issue your facing is that you havent done the initial "dance" to authorize that credentials.json with google.

the expected file in `credential_path` is NOT `credentials.json` but a file created during this first dance

I have a PR to allow this module to instigate that dance if your token hasnt been generated #689 
in the mean time until its merged, you can install from https://github.com/chestm007/i3pystatus/tree/google-calendar#branch=google-calendar

obviously on the google-calendar branch.

**Comment by chestm007** [comment]
fixed in #689, merged to master. i'll leave this issue open for a week or so just incase
