### ISSUE TITLE
Mail module stuck

### ISSUE THREAD

**Issue by vestingz** [enkore/i3pystatus#450]
From time to time mail module returns "Mail: error: command SEARCH illegal in state LOGOUT, only allowed in states SELECTED". To get it working again i have to reload my config.

**Comment by sileht** [comment]
Perhaps this will fix your issue https://github.com/enkore/i3pystatus/pull/452

**Comment by vestingz** [comment]
@sileht Thank you very much! :)

**Comment by vestingz** [comment]
Works very well most of the times now, but once in a while i get this error: RuntimeError: generator didn't yield. Usually it disappears after the next update but sometimes only reloading i3 helps.

**Comment by chestm007** [comment]
```
2018-12-25 04:43:59,676 [ERROR   ][i3pystatus.mail.Mail 100] Exception in Thread-6 at Tue 25 Dec 2018 04:43:59 AEDT, module Mail
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/i3pystatus/core/threading.py", line 92, in __call__
    self.workload()
  File "/usr/lib/python3.7/site-packages/i3pystatus/core/modules.py", line 297, in __call__
    self.run()
  File "/usr/lib/python3.7/site-packages/i3pystatus/mail/__init__.py", line 62, in run
    temp = backend.unread or 0
  File "/usr/lib/python3.7/site-packages/i3pystatus/core/util.py", line 364, in wrapper
    return method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/i3pystatus/mail/imap.py", line 96, in unread
    with self.ensure_connection():
  File "/usr/lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
```

Leaving this here for reference as i just hit this issue also

**Comment by vestingz** [comment]
Different, but possibly related: [#704](https://github.com/enkore/i3pystatus/issues/704).

**Comment by vestingz** [comment]
Thank you very much for the fix :) It seems not to occur anymore, but instead see above.
