### ISSUE TITLE
mail/imap crash when there's no internet

### ISSUE THREAD

**Issue by bel3atar** [enkore/i3pystatus#468]
```
Traceback (most recent call last):
  File ".config/i3pystatus/config.py", line 28, in <module>
    host="...", username="...", password="..."
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/settings.py", line 109, in __init__
    self.init()
  File "/usr/lib/python3.5/site-packages/i3pystatus/mail/imap.py", line 87, in init
    self.conn = self.get_connection()
  File "/usr/lib/python3.5/site-packages/i3pystatus/mail/imap.py", line 108, in get_connection
    self.connection = self.imap_class(self.host, self.port)
  File "/usr/lib/python3.5/imaplib.py", line 1269, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python3.5/imaplib.py", line 189, in __init__
    self.open(host, port)
  File "/usr/lib/python3.5/imaplib.py", line 1282, in open
    IMAP4.open(self, host, port)
  File "/usr/lib/python3.5/imaplib.py", line 286, in open
    self.sock = self._create_socket()
  File "/usr/lib/python3.5/imaplib.py", line 1272, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/lib/python3.5/imaplib.py", line 276, in _create_socket
    return socket.create_connection((self.host, self.port))
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by vestingz** [comment]
Might it be related to this? [https://github.com/enkore/i3pystatus/issues/450#issuecomment-253982252](url)
