### ISSUE TITLE
Alsa error kiiling whole output

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#488]
Just pulled i3pystatus and relaunched.

I don't care about the error by itself, just that it kills the whole output, is there a way to preven that in a generic way or ?
```
2016-10-25 12:56:45,290 [ERROR   ][i3pystatus.alsa.ALSA 76] Exception in Thread-2 at mar. 25 oct. 2016 12:56:45 CEST, module ALSA
Traceback (most recent call last):
  File "/home/teto/i3pystatus/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/home/teto/i3pystatus/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/home/teto/i3pystatus/i3pystatus/alsa.py", line 80, in run
    self.create_mixer()
  File "/home/teto/i3pystatus/i3pystatus/alsa.py", line 77, in create_mixer
    control=self.mixer, id=self.mixer_id, cardindex=self.card)
alsaaudio.ALSAAudioError: No such file or directory [hw:0]
```

**Comment by teto** [comment]
no that was not the issue sorry :
