### ISSUE TITLE
Error: status_command process exited unexpectedly

### ISSUE THREAD

**Issue by jcf** [enkore/i3pystatus#490]
When something goes wrong with a single module the entire status line can be brought down.

In my case the "Master" mixer can't be found, which in turn blows up alsaaudio, which then takes down all of my modules.

```
Traceback (most recent call last):
  File "/home/jcf/.config/i3/status.py", line 18, in <module>
    format=smaller("Vol {volume} / 100"))
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/__init__.py", line 110, in register
    return self.modules.append(module, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/util.py", line 73, in append
    module, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/imputil.py", line 47, in instanciate_class_from_module
    return self.instanciate_class_from_module(self.get_module(module), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/imputil.py", line 45, in instanciate_class_from_module
    return self.get_class(module)(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/modules.py", line 64, in __init__
    super(Module, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/settings.py", line 109, in __init__
    self.init()
  File "/usr/lib/python3.5/site-packages/i3pystatus/alsa.py", line 59, in init
    self.create_mixer()
  File "/usr/lib/python3.5/site-packages/i3pystatus/alsa.py", line 77, in create_mixer
    control=self.mixer, id=self.mixer_id, cardindex=self.card)
alsaaudio.ALSAAudioError: Unable to find mixer control Master,0 [hw:0]
```

I'll see if I can fix the underlying issue with my audio environment, but wonder if the experience could be a little more polished when something like this occurs?
I'm not familiar with the internals of i3pystatus so can only guess if it's even possible.

Thanks for i3pystatus!

**Comment by jcf** [comment]
Thanks, @facetoe!
