### ISSUE TITLE
after python updates on my system i3pystatus crashes

### ISSUE THREAD

**Issue by 2Belette** [enkore/i3pystatus#516]
My system (Parabola / ArchLinux based) get a bunch of python package updates today and after that my i3pystatus is not working anymore..

```
Python 3.6.0 (default, Dec 24 2016, 08:03:08) 
[GCC 6.2.1 20160830] on linux
```

```
python /home/user/.config/i3/status.py   
Traceback (most recent call last):
  File "/home/user/.config/i3/status.py", line 12, in <module>
    format="{percentage}%",)
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/__init__.py", line 110, in register
    return self.modules.append(module, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/util.py", line 73, in append
    module, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/imputil.py", line 47, in instanciate_class_from_module
    return self.instanciate_class_from_module(self.get_module(module), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/imputil.py", line 45, in instanciate_class_from_module
    return self.get_class(module)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/modules.py", line 64, in __init__
    super(Module, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/settings.py", line 109, in __init__
    self.init()
  File "/usr/lib/python3.6/site-packages/i3pystatus/backlight.py", line 50, in init
    with open(self.base_path + maxbfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/backlight/acpi_video0/max_brightness'
```

**Comment by enkore** [comment]
You probably need to adjust the `backlight` option of the [backlight](http://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#module-i3pystatus.backlight) module.

Or, if there is a `/sys/class/backlight/acpi_video0/` directory but no `max_brightness` file in there then it's a kernel problem.

**Comment by 2Belette** [comment]
you are right when I comment the `backlight` section then I got another error with the `clock` section.
```

  File "/usr/lib/python3.6/site-packages/i3pystatus/clock.py", line 100, in _expand_format
    raise RuntimeError("Need `pytz` for timezone data") from e
RuntimeError: Need `pytz` for timezone data
```

commenting it as well and i3pystatus works again.

Definitely something change somewhere in python as it was working correctly before the updates

**Comment by 2Belette** [comment]
adding 
`    backlight="intel_backlight",`
to backlight module solves the issue!
strange that I hadn't the issue before !
thanks

**Comment by enkore** [comment]
Yeah sometimes stuff in the kernel changes and things move around in /sys.

pytz: When installing through pip packages won't automatically upgrade with a new major Python release (eg. 3.5 -> 3.6); system packages do that (pacman -S ... python-pytz), but might be outdated (not really a big problem with Arch) or not available.

**Comment by 2Belette** [comment]
exactly what I discovered :) 
many thanks again enkore !
