### ISSUE TITLE
import problems?

### ISSUE THREAD

**Issue by pazz** [enkore/i3pystatus#540]
I get the following traceback when calling the i3pystatus script on its own.

```
i3pystatus                         
Traceback (most recent call last):
  File "/home/pazz/.local/bin/i3pystatus", line 7, in <module>
    from i3pystatus import main
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/__init__.py", line 3, in <module>
    from i3pystatus.core import Status
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/core/__init__.py", line 4, in <module>
    from threading import Thread
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/core/threading.py", line 5, in <module>
    from i3pystatus.core.util import partition
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/core/util.py", line 7, in <module>
    from threading import Timer, RLock
ImportError: cannot import name Timer
```

However, I have no problem to import this directly in python:

```
[~] python3                                                                                                          1 ↵  
Python 3.5.3rc1 (default, Jan  3 2017, 04:40:57) 
[GCC 6.3.0 20161229] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from threading import Timer, RLock
>>> 
[~]                                                                                                                       
[~] python2                                                                                                               
Python 2.7.13 (default, Dec 18 2016, 20:19:42) 
[GCC 6.2.1 20161215] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from threading import Timer, RLock
>>> 
```

I am on debian testing and installed via pip (also tried with git master).
Ideas?

**Comment by pazz** [comment]
When I try to run the [example config from your docs](http://i3pystatus.readthedocs.io/en/latest/configuration.html), I get a similar error:

```
python .i3/pyi3status.py                                                                                         1 ↵  
Traceback (most recent call last):
  File ".i3/pyi3status.py", line 2, in <module>
    from i3pystatus import Status
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/__init__.py", line 3, in <module>
    from i3pystatus.core import Status
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/core/__init__.py", line 4, in <module>
    from threading import Thread
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/core/threading.py", line 5, in <module>
    from i3pystatus.core.util import partition
  File "/home/pazz/.local/lib/python2.7/site-packages/i3pystatus/core/util.py", line 7, in <module>
    from threading import Timer, RLock
ImportError: cannot import name Timer
```

**Comment by pazz** [comment]
Ah got it! #430 suggests that I shouldn't use python 2 at all. sorry for the noise.

**Comment by enkore** [comment]
To be fair, it's pretty much the second sentence in the readme. It isn't mentioned prominently in the rtfd docs though, we should maybe do that.

> https://github.com/enkore/i3pystatus#installation
