### ISSUE TITLE
Add ability to show mixer capture status to alsa module

### ISSUE THREAD

**Issue by danielnelson** [enkore/i3pystatus#572]
It would be nice to be able to show if you are currently capturing in the status bar.  If I try to add my "Capture" mixer like this:

```python
status.register("alsa", mixer='Capture')
```

Then I get this error:
```
2017-05-14 15:52:12,773 [ERROR   ][i3pystatus.alsa.ALSA 76] Exception in Thread-2 at Sun 14 May 2017 03:52:12 PM PDT, module ALSA
Traceback (most recent call last):
  File "/home/dbn/.local/lib/python3.6/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/home/dbn/.local/lib/python3.6/site-packages/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/home/dbn/.local/lib/python3.6/site-packages/i3pystatus/alsa.py", line 86, in run
    self.fdict["volume"] = self.get_cur_volume()
  File "/home/dbn/.local/lib/python3.6/site-packages/i3pystatus/alsa.py", line 120, in get_cur_volume
    return self.alsamixer.getvolume()[self.channel]
IndexError: list index out of range
```

I would like to be able to specify a `capture` and `nocapture` setting which would contain the strings for a new `{capture}` placeholder depending on the current capture status.

**Comment by lasers** [comment]
I'm not familiar with i3pystatus, but https://github.com/lasers/i3pystatus/tree/alsa does what you want
```python
status.register("alsa", mixer="Capture")
status.register("alsa")
```

Maybe someone else can take over this branch and clean up things?

**Comment by chestm007** [comment]
@lasers  throw up a PR and i'll take a look :+1:
