### ISSUE TITLE
Mail socket error (err 32) Broken pipe

### ISSUE THREAD

**Issue by mihok** [enkore/i3pystatus#573]
I get this error from the mail modules specifically, and sporadically. Is there a workaround to prevent this? Usually reloading i3 fixes the problem but its annoying to have to do that every time.

I'm using `imap` and connecting to gmail for context

**Comment by enkore** [comment]
Installing imaplib2 might help, not sure.

**Comment by mihok** [comment]
Hmm, tried installing imaplib2 and now receive this error:

```python
  01:08.03 imap.googlemail.com reader last 20 log messages:
Traceback (most recent call last):
  File "/usr/bin/i3pystatus", line 11, in <module>
    load_entry_point('i3pystatus==3.35', 'console_scripts', 'i3pystatus')()
  File "/usr/lib/python3.6/site-packages/i3pystatus/__init__.py", line 47, in main
    imp.load_source(module_name, args.config)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/mihok/.config/i3/status.py", line 228, in <module>
    account='PERSONAL',
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/settings.py", line 109, in __init__
    self.init()
  File "/usr/lib/python3.6/site-packages/i3pystatus/mail/imap.py", line 87, in init
    self.conn = self.get_connection()
  File "/usr/lib/python3.6/site-packages/i3pystatus/mail/imap.py", line 108, in get_connection
    self.connection = self.imap_class(self.host, self.port)
  File "/usr/lib/python3.6/site-packages/imaplib2/imaplib2.py", line 2086, in __init__
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)
  File "/usr/lib/python3.6/site-packages/imaplib2/imaplib2.py", line 388, in __init__
    self.welcome = self._request_push(tag='continuation').get_response('IMAP4 protocol error: %s')[1]
  File "/usr/lib/python3.6/site-packages/imaplib2/imaplib2.py", line 187, in get_response
    self.ready.wait(sys.float_info.max)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timestamp too large to convert to C _PyTime_t
```
