### ISSUE TITLE
i3pystatus.mail: TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by vestingz** [enkore/i3pystatus#704]
```
2019-01-07 15:14:23,314 [ERROR   ][i3pystatus.mail.Mail 100] Exception in Thread-5 at Mon 07 Jan 2019 03:14:23 PM CET, module Mail
Traceback (most recent call last):
  File "/home/julian/.local/lib/python3.7/site-packages/i3pystatus/core/threading.py", line 92, in __call__
    self.workload()
  File "/home/julian/.local/lib/python3.7/site-packages/i3pystatus/core/modules.py", line 297, in __call__
    self.run()
  File "/home/julian/.local/lib/python3.7/site-packages/i3pystatus/mail/__init__.py", line 63, in run
    unread = unread + backend.unread
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

Occurs predominantly in situations with unstable wifi. I am using the version after [this](https://github.com/enkore/i3pystatus/commit/c275c31a5057cbd8a2eb1125e3f27b3f7e23f458) commit.

**Comment by chestm007** [comment]
Hi, that's unusual as line 63 in `mail/__init__.py` was changed too ` unread = unread + temp` 4 commits prior to the one you mentioned your running - this behaviour was why that line got changed :)

**Comment by vestingz** [comment]
You are absolutely right, please excuse this wasted issue! Thanks for the good work :)

**Comment by chestm007** [comment]
all good :)
