### ISSUE TITLE
mpd module emits error when icy-title's charset is not UTF-8.

### ISSUE THREAD

**Issue by crocket** [enkore/i3pystatus#744]
For many asian radio streams, icy-title's character encoding is not UTF-8.

The error is

```
2019-05-13 18:22:03,971 [ERROR   ][i3pystatus.mpd.MPD 100] Exception in Thread-4 at Mon May 13 18:22:03 2019, module MPD
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/i3pystatus/core/threading.py", line 92, in __call__
    self.workload()
  File "/usr/lib64/python3.6/site-packages/i3pystatus/core/modules.py", line 297, in __call__
    self.run()
  File "/usr/lib64/python3.6/site-packages/i3pystatus/mpd.py", line 155, in run
    "title": currentsong.get("Title", ""),
AttributeError: 'NoneType' object has no attribute 'get'
```

It's better to display broken characters than to emit errors.

**Comment by enkore** [comment]
80a0583 should at least prevent the exception, but will result in no current song information. I'm unsure how a proper fix would look like; MPD says the protocol is UTF-8, but seems to serve up non-UTF-8 at times?

**Comment by crocket** [comment]
There is no way to specify character encoding for icy-title in an m3u playlist in mpd.

https://github.com/MusicPlayerDaemon/MPD/issues/422

**Comment by crocket** [comment]
I installed the latest git commit, and the issue seems to have been fixed. I see broken characters instead of error. I will let you decide whether the issue is fixed.

**Comment by crocket** [comment]
Closing it because it is considered fixed.
