### ISSUE TITLE
xkblayout is broken on python 3.8.1, works on 3.8.0

### ISSUE THREAD

**Issue by werman** [enkore/i3pystatus#771]
Upgrading python from 3.8.0 to 3.8.1 broke xkblayout plugin, to be precise it's xkbgroup which is broken.

```
>>> from xkbgroup import XKeyboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/xkbgroup/__init__.py", line 14, in <module>
    from .core import XKeyboard, X11Error
  File "/usr/lib/python3.8/site-packages/xkbgroup/core.py", line 31, in <module>
    from .xkb import *
  File "/usr/lib/python3.8/site-packages/xkbgroup/xkb.py", line 3372, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```

**Comment by enkore** [comment]
I opened a ticket upstream.
