### ISSUE TITLE
Weather submodules issues

### ISSUE THREAD

**Issue by elig0n** [enkore/i3pystatus#803]
**1)** Using the [Weather underground example from the docs](https://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#module-i3pystatus.weather.wunderground) would complain that `update_error` is an invalid option:

```
Traceback (most recent call last):
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/settings.py", line 94, in __init__
    sm.update(settings_source)
  File "/usr/lib/python3.9/_collections_abc.py", line 856, in update
    self[key] = other[key]
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/util.py", line 111, in __setitem__
    raise KeyError(key)
KeyError: 'update_error'

Traceback (most recent call last):
  File "/home/e/.config/i3status/scripts/net.py", line 36, in <module>
    backend=wunderground.Wunderground(
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/modules.py", line 64, in __init__
    super(Module, self).__init__(*args, **kwargs)
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/settings.py", line 96, in __init__
    raise ConfigKeyError(type(self).__name__, key=exc.args[0]) from exc
i3pystatus.core.exceptions.ConfigKeyError: "Module 'Wunderground': invalid option 'update_error'"
```

**2)** Removing `update_error` would then complain about `api_key`

```
Traceback (most recent call last):
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/settings.py", line 99, in __init__
    self.__dict__.update(sm)
  File "/usr/lib/python3.9/_collections_abc.py", line 741, in __iter__
    yield from self._mapping
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/util.py", line 121, in __iter__
    raise self.MissingKeys(self.missing())
i3pystatus.core.util.MissingKeys: {'api_key'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/e/.config/i3status/scripts/net.py", line 36, in <module>
    backend=wunderground.Wunderground(
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/modules.py", line 64, in __init__
    super(Module, self).__init__(*args, **kwargs)
  File "/home/e/.local/lib/python3.9/site-packages/i3pystatus/core/settings.py", line 101, in __init__
    raise ConfigMissingError(
i3pystatus.core.exceptions.ConfigMissingError: Module 'Wunderground': missing required options: {'api_key'}
```

Which I understand is meant to be no longer required.

**3)** Using Weathercom backend example yields a parser error inside the outputted JSON:

```
, {"full_text": "Weather: ParseError: syntax error: line 1, column 0", "color": "#FF0000", "name": "i3pystatus.weather.Weather", "instance": "139671707571152", "markup": "pango"}, 
```

**Comment by terminalmage** [comment]
1. I'm using `update_error` with no problem. Make sure that you're using it when instantiating the `Wunderground` instance and not as an argument to `register()`.

2. The very link that you posted has a big green **Note** box that says:

   ```
   Previous versions of this module required an API key to work. Weather
   Underground has since discontinued their API, and this module has been
   rewritten to reflect that.
   ```

   In addition, the `api_key` item is no longer listed as an argument in the docs.

   To me this makes it seem pretty clear that `api_key` is not a valid config option, but I'm open to suggestions on how to improve the docs here.


3. Again, I can't reproduce this. Perhaps sharing your `register()` call for the weather module might help? I obviously haven't tested with all possible location codes, so it's possible that certain ones produce differently-formatted data which the module isn't parsing correctly.

**Comment by elig0n** [comment]
>     1. I'm using `update_error` with no problem. Make sure that you're using it when instantiating the `Wunderground` instance and not as an argument to `register()`.

Indeed, I copy-pasted the example.

>     2. The very link that you posted has a big green **Note** box that says:
>        In addition, the `api_key` item is no longer listed as an argument in the docs.
>        To me this makes it seem pretty clear that `api_key` is not a valid config option, but I'm open to suggestions on how to improve the docs here.

Hey, it wasn't me who complained about the `api_key` but `i3pystatus.core.util`.
I was asking, since the note box is so clear and I can't just wonder why does it even complain about this?

>     3. Again, I can't reproduce this. Perhaps sharing your `register()` call for the weather module might help? I obviously haven't tested with all possible location codes, so it's possible that certain ones produce differently-formatted data which the module isn't parsing correctly.

I've used the exact example given, with the same location code. Here it is anyway:
```
status.register(
    'weather',
    format='{condition} {current_temp}{temp_unit}[ {icon}][ Hi: {high_temp}][ Lo: {low_temp}][ {update_error}]',
    colorize=True,
    hints={'markup': 'pango'},
    backend=wunderground.Wunderground(
        location_code='KMACAMBR4',
        units='imperial',
        update_error='<span color="#ff0000">!</span>',
    ),
)
```

**Comment by elig0n** [comment]
Trying to invoke the backend manually in an interpreter results in:

```
Python 3.9.1 (default, Dec 13 2020, 11:55:53)
@>>> from i3pystatus.weather import wunderground
@>>> wunderground.Wunderground()
    Traceback (most recent call last):
    File ".../.local/lib/python3.9/site-packages/i3pystatus/core/settings.py", line 99, in __init__
    self.__dict__.update(sm)
    File "/usr/lib/python3.9/_collections_abc.py", line 741, in __iter__
    yield from self._mapping
    File ".../.local/lib/python3.9/site-packages/i3pystatus/core/util.py", line 121, in __iter__
    raise self.MissingKeys(self.missing())
    i3pystatus.core.util.MissingKeys: {'location_code', 'api_key'}

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
    File ".../.local/lib/python3.9/site-packages/i3pystatus/core/modules.py", line 64, in __init__
        super(Module, self).__init__(*args, **kwargs)
        File ".../.local/lib/python3.9/site-packages/i3pystatus/core/settings.py", line 101, in __init__
        raise ConfigMissingError(
                i3pystatus.core.exceptions.ConfigMissingError: Module 'Wunderground': missing required options: {'location_code', 'api_key'}
```

**Comment by terminalmage** [comment]
It seems like you're not running i3pystatus from the `current` branch. There is no reference to `api_key` in the code any more, so there is no possible way that error would appear unless you are running an older version of i3pystatus.

**Comment by elig0n** [comment]
I had two modules installed, local and global. I upgraded both but it didn't help. So I removed my .local/ module and now using the system-wide module the problem is gone.
